export interface BlogPost {
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  category: "Product Updates" | "AI Research" | "GEO & Search" | "Engineering & Infrastructure" | "Guides & Tutorials";
  publishDate: string;
  readTime: string;
  author: {
    name: string;
    role: string;
    avatar: string;
    bio: string;
  };
  featured?: boolean;
  coverImage: string;
  tags: string[];
}

export const BLOG_CATEGORIES = [
  "All",
  "Product Updates",
  "AI Research",
  "GEO & Search",
  "Engineering & Infrastructure",
  "Guides & Tutorials",
] as const;

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: "nano-banana-pro",
    title: "Nano Banana Pro in Google Antigravity: Multimodal Agentic Workflows & Visual Automation",
    excerpt:
      "Introducing Nano Banana Pro integration in Google Antigravity. Explore how low-latency multimodal capabilities allow autonomous AI agents to design, audit, and visually verify web applications in real time.",
    category: "AI Research",
    publishDate: "Sep 28, 2026",
    readTime: "6 min read",
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    tags: ["Nano Banana Pro", "Google Antigravity", "Multimodal AI", "Agentic IDE"],
    author: {
      name: "Mohit Negi",
      role: "Lead AI Architect & Founder",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      bio: "Pioneering enterprise IT infrastructure and AI agent architectures at Comptech Enterprises for over 15 years.",
    },
    content: `
<p class="lead text-xl text-gray-600 leading-relaxed mb-6">
  Today we are detailing the integration of <strong>Nano Banana Pro</strong> within the Google Antigravity ecosystem. By pairing ultra-fast visual token comprehension with stateful agentic execution, businesses can now direct AI agents through real-time visual UI feedback and automated interface verification.
</p>

<h2 id="multimodal-agentic-loop" class="text-2xl font-bold text-gray-900 mt-10 mb-4">The Multimodal Agentic Execution Loop</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  In standard AI tools, models operate purely on text inputs and unstructured logs. Nano Banana Pro introduces <strong>live viewport inspection</strong>, enabling agents to verify rendering quality, layout responsiveness, and visual accessibility without human intervention.
</p>

<div class="my-8 p-6 rounded-2xl bg-slate-900 text-slate-100 shadow-xl border border-slate-800">
  <h4 class="font-bold text-emerald-400 text-lg mb-3">🚀 Key Capabilities of Nano Banana Pro</h4>
  <ul class="space-y-2.5 text-sm text-slate-300">
    <li>• <strong>Real-time Visual Auditing:</strong> Automatically detects layout misalignments and color contrast accessibility gaps directly from visual DOM renders.</li>
    <li>• <strong>Sub-Second Vision Processing:</strong> Encodes user interfaces in under 120ms for rapid, real-time agent responses.</li>
    <li>• <strong>Multi-Device Responsive Verification:</strong> Evaluates rendering across Mobile, Tablet, and Desktop breakpoints simultaneously.</li>
  </ul>
</div>

<h2 id="workflow-integration" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Workflow Integration & Antigravity Operations</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  Rather than writing manual test scripts, team leaders can set high-level visual standards for their enterprise applications. The agent continuously monitors target viewports, identifies layout anomalies, and automatically proposes visual optimizations.
</p>

<div class="my-8 p-6 rounded-2xl bg-emerald-50 border border-emerald-200">
  <h4 class="font-bold text-emerald-900 text-lg mb-2">💡 Operational Workflow Advantage</h4>
  <p class="text-sm text-emerald-800 leading-relaxed">
    Designers and product managers can review side-by-side visual diffs generated by the AI agent, cutting visual QA audit cycles from 3 days down to 15 minutes.
  </p>
</div>

<h2 id="benchmarks" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Performance Benchmarks</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  Compared to legacy vision models, Nano Banana Pro achieves:
</p>
<ul class="list-disc pl-6 space-y-2 text-gray-700 mb-6">
  <li><strong>3.8x Speed Improvement</strong> on DOM visual element identification.</li>
  <li><strong>98.7% Accuracy</strong> on cross-browser layout alignment verification.</li>
  <li><strong>Zero Memory Bottlenecks</strong> during long-horizon iterative subagent runs.</li>
</ul>

<h2 id="conclusion" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Summary</h2>
<p class="text-gray-700 leading-relaxed mb-6">
  Nano Banana Pro represents a major milestone in agentic engineering, turning visual interface quality assurance from a manual bottleneck into an automated, verifiable pipeline.
</p>
`,
  },
  {
    slug: "gemini-3-8-flash-enterprise-ai-integration",
    title: "Gemini 3.8 Flash in Comptech AI Suite: Accelerating MSME & Enterprise Workflows",
    excerpt:
      "How integrating Google's latest Gemini 3.8 Flash model into our autonomous agent framework yields 4x faster response times, sub-second tool execution, and 60% lower latency for enterprise workflows.",
    category: "Product Updates",
    publishDate: "Sep 24, 2026",
    readTime: "5 min read",
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80",
    tags: ["Gemini 3.8", "AI Agents", "Enterprise Workflows", "LLM Benchmark"],
    author: {
      name: "Mohit Negi",
      role: "Lead AI Architect & Founder",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      bio: "Pioneering enterprise IT infrastructure and AI agent architectures at Comptech Enterprises for over 15 years.",
    },
    content: `
<p class="lead text-xl text-gray-600 leading-relaxed mb-6">
  Today we are excited to announce full native support for <strong>Google's Gemini 3.8 Flash</strong> across the Comptech Enterprise AI platform. By combining ultra-low-latency inference with function-calling precision, businesses can now run continuous autonomous workflows without throughput bottlenecks.
</p>

<h2 id="why-gemini-38" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Why Speed & Context Matter for Enterprise Agents</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  In production environments, an AI agent rarely executes a single prompt. A typical customer service or CRM automation agent performs a chain of multi-step operations: querying internal databases, parsing unstructured PDFs, verifying business logic, and outputting structured payloads.
</p>
<p class="text-gray-700 leading-relaxed mb-6">
  With traditional models, multi-step agent chains could take 8 to 15 seconds to execute. Gemini 3.8 Flash reduces multi-turn latency to under <strong>1.2 seconds</strong> while retaining a 1-million token context window.
</p>

<div class="my-8 p-6 rounded-2xl bg-emerald-50 border border-emerald-200">
  <h4 class="font-bold text-emerald-900 text-lg mb-2">⚡ Benchmark Highlights</h4>
  <ul class="space-y-2 text-sm text-emerald-800">
    <li>• <strong>4.2x faster token generation</strong> compared to legacy enterprise models.</li>
    <li>• <strong>99.4% structured output accuracy</strong> for automated ERP & CRM integrations.</li>
    <li>• <strong>60% reduction in token costs</strong> for batch data processing.</li>
  </ul>
</div>

<h2 id="architecture-overview" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Automated Inventory & ERP Lookup Pipeline</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  Instead of manual inventory verification, our AI Agent engine connects directly with warehouse ERP APIs. When a customer requests availability for enterprise servers or networking components, the agent executes an automated 3-step pipeline:
</p>

<div class="my-8 overflow-hidden rounded-2xl border border-gray-200 bg-gray-50 p-6 space-y-4">
  <div class="flex items-start gap-3">
    <div class="w-7 h-7 rounded-full bg-emerald-600 text-white font-bold flex items-center justify-center shrink-0 text-xs">1</div>
    <div>
      <h5 class="font-bold text-gray-900 text-sm">Query Parsing & Intent Recognition</h5>
      <p class="text-xs text-gray-600">Extracts exact SKU, hardware specification, and quantity requirements from incoming emails or WhatsApp chats.</p>
    </div>
  </div>
  <div class="flex items-start gap-3">
    <div class="w-7 h-7 rounded-full bg-emerald-600 text-white font-bold flex items-center justify-center shrink-0 text-xs">2</div>
    <div>
      <h5 class="font-bold text-gray-900 text-sm">Real-time Stock Verification</h5>
      <p class="text-xs text-gray-600">Queries Delhi warehouse ERP stock databases securely in under 200ms.</p>
    </div>
  </div>
  <div class="flex items-start gap-3">
    <div class="w-7 h-7 rounded-full bg-emerald-600 text-white font-bold flex items-center justify-center shrink-0 text-xs">3</div>
    <div>
      <h5 class="font-bold text-gray-900 text-sm">Instant Formal Quote Generation</h5>
      <p class="text-xs text-gray-600">Generates a branded PDF quotation with custom pricing tier discounts applied automatically.</p>
    </div>
  </div>
</div>

<h2 id="real-world-impact" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Real-World Impact Across MSMEs in India</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  Since deploying Gemini 3.8 Flash in our production agent suite, over 40 enterprise client deployments across Delhi NCR, Mumbai, and Bengaluru have reported:
</p>
<ul class="list-disc pl-6 space-y-2 text-gray-700 mb-6">
  <li><strong>Instant WhatsApp & Email Lead Qualification:</strong> Qualified responses delivered within 3 seconds of incoming client inquiries.</li>
  <li><strong>Automated Document Processing:</strong> Invoices and GST filing documents processed in real time without human intervention.</li>
  <li><strong>Seamless Hybrid Deployment:</strong> Integrates with local Dell & HP server clusters and VPCs for zero-data-leakage compliance.</li>
</ul>

<h2 id="getting-started" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Getting Started</h2>
<p class="text-gray-700 leading-relaxed mb-6">
  All existing Comptech AI Suite subscribers have been automatically upgraded to Gemini 3.8 Flash at no extra cost. If you are exploring custom AI agents for your business, contact our team for a live demonstration.
</p>
`,
  },
  {
    slug: "generative-engine-optimization-geo-guide-2026",
    title: "Generative Engine Optimization (GEO): The Definitive Guide for 2026",
    excerpt:
      "Traditional SEO ranks 10 blue links. GEO ensures your brand is directly cited and recommended by ChatGPT, Google Gemini, Perplexity, and Claude. Here is how entity optimization works.",
    category: "GEO & Search",
    publishDate: "Sep 20, 2026",
    readTime: "7 min read",
    coverImage: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    tags: ["GEO", "AI Search", "ChatGPT Citation", "SEO vs GEO"],
    author: {
      name: "Rohit Sharma",
      role: "Head of Growth & GEO Strategy",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      bio: "Specialist in AI entity knowledge graph optimization and LLM citation mechanics.",
    },
    content: `
<p class="lead text-xl text-gray-600 leading-relaxed mb-6">
  Over 40% of web searches are now performed directly within conversational AI interfaces like ChatGPT, Google Gemini, and Perplexity AI. If your business isn't structured as an authoritative entity in AI knowledge bases, you risk becoming completely invisible to modern buyers.
</p>

<h2 id="what-is-geo" class="text-2xl font-bold text-gray-900 mt-10 mb-4">What is Generative Engine Optimization?</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  <strong>Generative Engine Optimization (GEO)</strong> is the discipline of optimizing a brand's web content, entity footprint, structured data, and citations so that Large Language Models (LLMs) synthesize your business as the primary recommended solution when users ask relevant queries.
</p>

<div class="my-8 overflow-hidden rounded-2xl border border-gray-200 bg-gray-50 p-6">
  <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
    <div class="p-4 rounded-xl bg-white border border-gray-200">
      <h4 class="font-bold text-gray-500 uppercase text-xs tracking-wider mb-2">Traditional SEO</h4>
      <p class="text-sm text-gray-700">Optimizes for Google crawlers to rank on Page 1 blue links based on keywords and backlink volume.</p>
    </div>
    <div class="p-4 rounded-xl bg-emerald-50 border border-emerald-200">
      <h4 class="font-bold text-emerald-800 uppercase text-xs tracking-wider mb-2">Generative Engine Optimization (GEO)</h4>
      <p class="text-sm text-emerald-900 font-medium">Optimizes entity authority so LLMs directly cite and recommend your brand inside single synthesized answers.</p>
    </div>
  </div>
</div>

<h2 id="key-pillars-of-geo" class="text-2xl font-bold text-gray-900 mt-10 mb-4">The 4 Key Pillars of High-Citation GEO</h2>

<h3 class="text-xl font-semibold text-gray-800 mt-6 mb-2">1. Entity-Rich Knowledge Graph Footprint</h3>
<p class="text-gray-700 leading-relaxed mb-4">
  AI models rely on structured knowledge graphs (Wikipedia, Wikidata, official schema markups, domain registers) to verify facts. Creating clear organization and local business definitions ensures models index your exact capabilities.
</p>

<h3 class="text-xl font-semibold text-gray-800 mt-6 mb-2">2. Sourced Citation Quotes & Quantitative Data</h3>
<p class="text-gray-700 leading-relaxed mb-4">
  LLMs prioritize content containing explicit metrics, technical specifications, verified client results, and authoritative quotes. Vague marketing fluff is filtered out by compression algorithms during answer synthesis.
</p>

<h3 class="text-xl font-semibold text-gray-800 mt-6 mb-2">3. Direct Conversational Formatting</h3>
<p class="text-gray-700 leading-relaxed mb-4">
  Structure content to answer specific natural language prompts (e.g. <em>"Which IT agency in Delhi provides enterprise server AMC and AI agent development?"</em>). Using clear questions with immediate concise summary answers boosts LLM retrieval probabilities by up to 300%.
</p>

<h3 class="text-xl font-semibold text-gray-800 mt-6 mb-2">4. Multi-Platform Citation Syndication</h3>
<p class="text-gray-700 leading-relaxed mb-6">
  Perplexity and Gemini check real-time web sources. Sponsoring verified press releases, tech blogs, and industry directories creates consistent co-occurrences of your brand name alongside core service keywords.
</p>

<h2 id="measuring-geo" class="text-2xl font-bold text-gray-900 mt-10 mb-4">How Comptech Tracks AI Visibility</h2>
<p class="text-gray-700 leading-relaxed mb-6">
  Our specialized <strong>GEO Analytics Engine</strong> runs daily automated prompt sweeps across ChatGPT, Gemini, Perplexity, Copilot, and Claude. We measure:
</p>
<ul class="list-disc pl-6 space-y-2 text-gray-700 mb-6">
  <li><strong>Citation Rate (%):</strong> Frequency of your brand appearing in top 3 recommended sources.</li>
  <li><strong>Sentiment Score:</strong> Tone and accuracy of AI recommendations.</li>
  <li><strong>Share of Voice:</strong> Percentage of sector queries won vs key competitors.</li>
</ul>
`,
  },
  {
    slug: "building-autonomous-sales-support-ai-agents",
    title: "Building Autonomous Sales & Support AI Agents with Human-in-the-Loop Safeguards",
    excerpt:
      "A deep dive into building production-ready AI sales agents that handle lead qualification, WhatsApp follow-ups, and calendar booking while preserving full audit control.",
    category: "AI Research",
    publishDate: "Sep 15, 2026",
    readTime: "8 min read",
    coverImage: "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80",
    tags: ["AI Agents", "Sales Automation", "Human-in-the-loop", "Workflow Safeguards"],
    author: {
      name: "Mohit Negi",
      role: "Lead AI Architect & Founder",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      bio: "Pioneering enterprise IT infrastructure and AI agent architectures at Comptech Enterprises for over 15 years.",
    },
    content: `
<p class="lead text-xl text-gray-600 leading-relaxed mb-6">
  Deploying AI agents in customer-facing roles requires more than simple prompt instructions. To prevent hallucinations and brand risks, enterprise agents require stateful execution workflows and deterministic Human-in-the-Loop (HITL) approval boundaries.
</p>

<h2 id="agentic-architecture" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Stateful Workflow Routing</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  Instead of simple single-turn chatbot responses, modern agents operate on structured workflow stages: Lead Inbound, Qualification, Calendar Discovery, and Proposal Dispatch.
</p>

<div class="my-8 p-6 rounded-2xl bg-[#5C0F26] text-white shadow-xl">
  <h4 class="font-bold text-amber-300 text-lg mb-3">🛡️ Enterprise Guardrails & Approval Matrix</h4>
  <div class="space-y-3 text-xs">
    <div class="p-3 rounded-lg bg-white/10 border border-white/15">
      <span class="font-bold text-amber-300 block mb-1">Standard Quotes (&lt; ₹50,000):</span>
      <span class="text-gray-200">AI Agent automatically checks ERP stock, applies standard pricing tier, and dispatches quotation directly via WhatsApp.</span>
    </div>
    <div class="p-3 rounded-lg bg-white/10 border border-white/15">
      <span class="font-bold text-amber-300 block mb-1">High-Value Contracts (&gt; ₹50,000):</span>
      <span class="text-gray-200">AI Agent drafts proposal, flags custom discount request, and routes to Sales Director Slack/WhatsApp for 1-click human approval.</span>
    </div>
  </div>
</div>

<h2 id="key-takeaways" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Key Takeaways for Enterprise Deployments</h2>
<ul class="list-disc pl-6 space-y-2 text-gray-700 mb-6">
  <li>Never give raw AI outputs direct write permissions to production CRMs without schema validation.</li>
  <li>Always maintain an audit trailing log of all agent actions and reasoning steps.</li>
  <li>Set hard spending limits and rate-limit guardrails per session.</li>
</ul>
`,
  },
  {
    slug: "enterprise-cloud-hybrid-it-infrastructure-security",
    title: "Enterprise Cloud & Hybrid IT Infrastructure: 2026 Security & AMC Checklist",
    excerpt:
      "As businesses scale hybrid cloud setups across Dell servers, Microsoft 365, and on-premise racks, proactive AMC and zero-trust firewall configurations are vital.",
    category: "Engineering & Infrastructure",
    publishDate: "Sep 10, 2026",
    readTime: "6 min read",
    coverImage: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80",
    tags: ["IT Infrastructure", "Dell Servers", "Cybersecurity", "AMC"],
    author: {
      name: "Pankaj Sharma",
      role: "Senior IT Infrastructure Lead",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80",
      bio: "Certified Dell & Cisco network engineer managing 200+ corporate server deployments across India.",
    },
    content: `
<p class="lead text-xl text-gray-600 leading-relaxed mb-6">
  Maintaining 99.99% uptime for enterprise networks across corporate offices, factories, and remote teams requires combining robust hardware redundancy with automated monitoring.
</p>

<h2 id="hardware-redundancy" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Dell & HP Server Redundancy Best Practices</h2>
<p class="text-gray-700 leading-relaxed mb-4">
  For mission-critical ERP systems, dual-socket Dell PowerEdge or HP ProLiant racks should always be configured with dual hot-swappable power supplies and high-speed NVMe storage arrays.
</p>
<ul class="list-disc pl-6 space-y-2 text-gray-700 mb-6">
  <li><strong>RAID 10 Protection:</strong> Mirrored and striped array ensuring zero data loss during disk failure.</li>
  <li><strong>Proactive AMC Monitoring:</strong> Sensor alerts for thermal spikes, fan failures, and voltage fluctuations.</li>
  <li><strong>Network Isolation:</strong> Segmenting IoT / CCTV networks away from core finance databases.</li>
</ul>
`,
  },
  {
    slug: "practical-ai-workshops-for-corporate-teams",
    title: "How Practical AI Workshops Transform Productivity in Non-Tech Corporate Teams",
    excerpt:
      "Why theoretical AI training fails, and how hands-on custom workflow workshops help finance, HR, and ops teams save 10+ hours per week per employee.",
    category: "Guides & Tutorials",
    publishDate: "Sep 02, 2026",
    readTime: "5 min read",
    coverImage: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?auto=format&fit=crop&w=1200&q=80",
    tags: ["AI Workshops", "Corporate Training", "Productivity", "Custom Workflows"],
    author: {
      name: "Rohit Sharma",
      role: "Head of Growth & GEO Strategy",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
      bio: "Specialist in AI entity knowledge graph optimization and LLM citation mechanics.",
    },
    content: `
<p class="lead text-xl text-gray-600 leading-relaxed mb-6">
  Most corporate AI training consists of generic prompt engineering slides. True productivity transformation happens when teams build tailored workflows using their company's exact documents.
</p>
<h2 id="workshop-outcomes" class="text-2xl font-bold text-gray-900 mt-10 mb-4">Key Outcomes from Comptech Corporate Workshops</h2>
<ul class="list-disc pl-6 space-y-2 text-gray-700 mb-6">
  <li>Finance teams automating vendor invoice reconciliation with vision AI models.</li>
  <li>HR teams drafting tailored offer letters and screening resumes 5x faster.</li>
  <li>Ops managers tracking fleet logistics using voice-to-text automated summaries.</li>
</ul>
`,
  },
  {
    slug: "building-custom-rag-pipeline-architecture",
    title: "Building Custom RAG Pipelines with Vector Search & Local LLM Privacy",
    excerpt:
      "Learn how to architect enterprise Retrieval-Augmented Generation (RAG) pipelines using Milvus vector storage, hybrid search, and local privacy-first model deployment.",
    category: "Engineering & Infrastructure",
    publishDate: "Aug 26, 2026",
    readTime: "9 min read",
    coverImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80",
    tags: ["RAG", "Vector Search", "Privacy", "Milvus", "AI"],
    author: {
      name: "Mohit Negi",
      role: "Lead AI Architect & Founder",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80",
      bio: "Pioneering enterprise IT infrastructure and AI agent architectures at Comptech Enterprises for over 15 years.",
    },
    content: `
<p class="lead text-xl text-gray-600 leading-relaxed mb-6">
  Data privacy is the single biggest barrier to enterprise AI adoption. By pairing hybrid vector search with locally hosted models on secure on-premise hardware, enterprises achieve high accuracy without leaking proprietary IP.
</p>
<h2 id="rag-pipeline-steps" class="text-2xl font-bold text-gray-900 mt-10 mb-4">5-Step Hybrid RAG Architecture</h2>
<ol class="list-decimal pl-6 space-y-2 text-gray-700 mb-6">
  <li>Document Chunking with Contextual Overlap.</li>
  <li>Dense Vector Embeddings via Enterprise Models.</li>
  <li>Sparse Keyword Search for Exact SKU & Product Specification Matching.</li>
  <li>Reciprocal Rank Fusion Reranking.</li>
  <li>Privacy-scoped Local AI Inference.</li>
</ol>
`,
  },
];
